name: flutter_webrtc_demo
description: A new Flutter application.
version: 1.2.0

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_webrtc: ^0.11.1
  shared_preferences: ^2.0.7
  http: ^0.13.3
  path_provider: ^2.0.2
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  url_launcher: 6.1.11
  permission_handler: 11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
